// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./components/StatusBar/index.vue')['default']
    Sudoku: typeof import('./components/Sudoku/index.vue')['default']
    SudokuItem: typeof import('./components/SudokuItem/index.vue')['default']
    SudokuTipBox: typeof import('./components/SudokuTipBox/index.vue')['default']
  }
}

export {}
